Traceback (most recent call last):
  File "/vscmnt/brussel_pixiu_data/_data_brussel/vo/000/bvo00012/vsc11137/source2suffering/main.py", line 310, in <module>
    exec(exe_exposure)
  File "<string>", line 136, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/data/brussel/vo/000/bvo00012/vsc11137/source2suffering/data/pickles_v3/burntarea/ds_EMF_percountry_GMT.pkl'
